import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nabar from "./component/Nabar";
import Hero from "./component/Hero/Hero";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "aos/dist/aos.css";
import Products from "./component/Product/Products";
import TopProducts from "./component/TopProducts/TopProducts";
import Banner from "./component/Banner/Banner";
import Subcribe from "./component/Subcribe/Subcribe";
import Testimonails from "./component/Testimonails/Testimonails";
import Footer from "./component/Footer/Footer";
// import AOS from "aos";
// import { useEffect } from "react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nabar />
        <Hero />
        <Products />
        <TopProducts />
        <Banner />
        <Subcribe />
        <Testimonails />
        <Footer />
        {children}
      </body>
    </html>
  );
}
